## Linear algebra review

We briefly review some necessary background in linear algebra. Let C be
an M × N matrix with real-valued entries; for a term-document matrix, all
RANK entries are in fact non-negative. The rank of a matrix is the number of linearly
independent rows (or columns) in it; thus, rank(C) ≤ min{M, N}. 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD

In [8]:
M = 5
N = 6
SEED = 0

np.random.seed(0)
C = np.random.randint(1,5,size=(M, N))
C

array([[1, 4, 2, 1, 4, 4],
       [4, 4, 2, 4, 2, 3],
       [1, 4, 3, 1, 1, 1],
       [3, 2, 3, 4, 4, 3],
       [1, 2, 2, 2, 2, 1]])

### Diagonal matrix

A square r × r matrix all of whose off-diagonal entries are zero is called a diagonal matrix; its rank is equal to the number of non-zero diagonal entries (rank = 5).

In [10]:
r = 4
np.random.seed(0)
C = np.random.randint(1,5,size=(r, r))
np.diag(np.diag(C))

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

### Identity matrix

If all r diagonal entries of such a diagonal matrix are 1, it is called the identity matrix of dimension r and represented by Ir.

In [12]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Eigenvalues and eigenvector

For a square M × M matrix C and a vector ~x that is not all zeros, the values of λ satisfying

C~x = λ~ (18.1)

are called the eigenvalues of C. The N-vector ~x satisfying Equation (18.1) for an eigenvalue λ is the corresponding right eigenvector. The eigenvector corresponding to the eigenvalue of largest magnitude is called the principal eigenvector. In a similar fashion, the left eigenvectors of C are the M-vectors y such that

yT C = λ~yT (18.2)

The number of non-zero eigenvalues of C is at most rank(C).

#### Found eigenvalues in matrix

 (C − λIM)~x = 0
 f |(C − λIM)| = 0
 
where |S| denotes the determinant of a square matrix S.

The equation is an Mth order polynomial equation in λ and can have at most M roots,
which are the eigenvalues of C. These eigenvalues can in general be complex,
even if all entries of C are real.

Example 18.1: Consider the matrix

In [49]:
S = np.array([[30, 0, 0],
              [0, 20, 0],
              [0, 0, 1]])
S

array([[30,  0,  0],
       [ 0, 20,  0],
       [ 0,  0,  1]])

Clearly the matrix has rank 3, and has 3 non-zero eigenvalues λ1 = 30, λ2 = 20 and
λ3 = 1, with the three corresponding eigenvectors

In [50]:
eigenvalues, eigenvectors = np.linalg.eig(S)
print("EigenValues: {}".format(eigenvalues))
print("""Eigenvectors: 
      x1 = {} 
      x2 = {} 
      x3 = {}""".format(eigenvectors[0],eigenvectors[1],eigenvectors[2]))

EigenValues: [ 30.  20.   1.]
Eigenvectors: 
      x1 = [ 1.  0.  0.] 
      x2 = [ 0.  1.  0.] 
      x3 = [ 0.  0.  1.]


For a symmetric matrix S, the eigenvectors corresponding to distinct eigenvalues
are orthogonal. Further, if S is both real and symmetric, the eigenvalues
are all real.


In [51]:
S = np.array([[2, 1],
              [1, 2]])
S

array([[2, 1],
       [1, 2]])

From the characteristic equation |S − λI| = 0, we have the quadratic (2 − λ)
2 − 1 =
0, whose solutions yield the eigenvalues 3 and 1.

In [52]:
eigenvalues, eigenvectors = np.linalg.eig(S)

In [53]:
eigenvalues

array([ 3.,  1.])

In [54]:
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [5]:
df = pd.DataFrame(data,columns=['d1','d2','d3','d4','d5','d6'], index=['ship','boat','ocean','voyage','trip'])

In [6]:
df

d1  d2  d3  d4  d5  d6
ship     1   0   1   0   0   0
boat     0   1   0   0   0   0
ocean    1   1   0   0   0   0
voyage   1   0   0   1   1   0
trip     0   0   0   1   0   1

In [8]:
svd = TruncatedSVD(2)
svd_desc = svd.fit_transform(df)

In [15]:
svd_desc

array([[ 0.95225185, -0.47221518],
       [ 0.2797116 , -0.52845914],
       [ 1.02833465, -0.81491313],
       [ 1.52028211,  0.55894647],
       [ 0.56803026,  1.03116165]])

In [16]:
np.linalg.svd(data)

(array([[  4.40347480e-01,  -2.96174360e-01,  -5.69497581e-01,
           5.77350269e-01,  -2.46402144e-01],
        [  1.29346349e-01,  -3.31450692e-01,   5.87021697e-01,
           1.11022302e-16,  -7.27197008e-01],
        [  4.75530263e-01,  -5.11115242e-01,   3.67689978e-01,
           1.11022302e-16,   6.14358412e-01],
        [  7.03020318e-01,   3.50572409e-01,  -1.54905878e-01,
          -5.77350269e-01,  -1.59788154e-01],
        [  2.62672838e-01,   6.46746769e-01,   4.14591704e-01,
           5.77350269e-01,   8.66139898e-02]]),
 array([ 2.16250096,  1.59438237,  1.27529025,  1.        ,  0.39391525]),
 array([[  7.48623048e-01,   2.79711603e-01,   2.03628802e-01,
           4.46563110e-01,   3.25095956e-01,   1.21467154e-01],
        [ -2.86453991e-01,  -5.28459139e-01,  -1.85761186e-01,
           6.25520701e-01,   2.19879758e-01,   4.05640944e-01],
        [ -2.79711603e-01,   7.48623048e-01,  -4.46563110e-01,
           2.03628802e-01,  -1.21467154e-01,   3.25095956e-01

In [19]:
np.linalg.svd(data)

(array([[  4.40347480e-01,  -2.96174360e-01,  -5.69497581e-01,
           5.77350269e-01,  -2.46402144e-01],
        [  1.29346349e-01,  -3.31450692e-01,   5.87021697e-01,
           1.11022302e-16,  -7.27197008e-01],
        [  4.75530263e-01,  -5.11115242e-01,   3.67689978e-01,
           1.11022302e-16,   6.14358412e-01],
        [  7.03020318e-01,   3.50572409e-01,  -1.54905878e-01,
          -5.77350269e-01,  -1.59788154e-01],
        [  2.62672838e-01,   6.46746769e-01,   4.14591704e-01,
           5.77350269e-01,   8.66139898e-02]]),
 array([ 2.16250096,  1.59438237,  1.27529025,  1.        ,  0.39391525]),
 array([[  7.48623048e-01,   2.79711603e-01,   2.03628802e-01,
           4.46563110e-01,   3.25095956e-01,   1.21467154e-01],
        [ -2.86453991e-01,  -5.28459139e-01,  -1.85761186e-01,
           6.25520701e-01,   2.19879758e-01,   4.05640944e-01],
        [ -2.79711603e-01,   7.48623048e-01,  -4.46563110e-01,
           2.03628802e-01,  -1.21467154e-01,   3.25095956e-01